// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using istore_api.src.Infrastructure.Data;

#nullable disable

namespace istore_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("istore_api.src.Domain.Models.BlogTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.DeviceModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("ProductCategoryName");

                    b.ToTable("DeviceModels");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.OptionsCombiningCharacteristic", b =>
                {
                    b.Property<string>("ImageFilename")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacteristicName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCharacteristicName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductImageFilename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImageFilename", "CharacteristicName");

                    b.HasIndex("ProductCharacteristicName");

                    b.HasIndex("ProductImageFilename");

                    b.ToTable("OptionsCombiningCharacteristics");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunicationMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("TotalSum")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.OrderProducts", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DeviceModelName");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.ProductCategory", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.ProductCharacteristic", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("ProductCharacteristics");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.ProductCharacteristicVariant", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacteristicName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrowthToValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId", "CharacteristicName");

                    b.HasIndex("CharacteristicName");

                    b.ToTable("ProductCharacteristicVariants");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.ProductImage", b =>
                {
                    b.Property<string>("Filename")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPreviewImage")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Filename");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.PromoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestoreCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RestoreCodeValidBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenValidBefore")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasPasswordResetRequest")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.DeviceModel", b =>
                {
                    b.HasOne("istore_api.src.Domain.Models.ProductCategory", "ProductCategory")
                        .WithMany("DeviceModels")
                        .HasForeignKey("ProductCategoryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.OptionsCombiningCharacteristic", b =>
                {
                    b.HasOne("istore_api.src.Domain.Models.ProductCharacteristic", "ProductCharacteristic")
                        .WithMany()
                        .HasForeignKey("ProductCharacteristicName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("istore_api.src.Domain.Models.ProductImage", "ProductImage")
                        .WithMany("OptionsCombiningCharacteristic")
                        .HasForeignKey("ProductImageFilename")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCharacteristic");

                    b.Navigation("ProductImage");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.OrderProducts", b =>
                {
                    b.HasOne("istore_api.src.Domain.Models.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("istore_api.src.Domain.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.Product", b =>
                {
                    b.HasOne("istore_api.src.Domain.Models.DeviceModel", "DeviceModel")
                        .WithMany("Products")
                        .HasForeignKey("DeviceModelName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceModel");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.ProductCharacteristicVariant", b =>
                {
                    b.HasOne("istore_api.src.Domain.Models.ProductCharacteristic", "Characteristic")
                        .WithMany("CharacteristicVariants")
                        .HasForeignKey("CharacteristicName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("istore_api.src.Domain.Models.Product", "Product")
                        .WithMany("CharacteristicVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characteristic");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.ProductImage", b =>
                {
                    b.HasOne("istore_api.src.Domain.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.DeviceModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.Product", b =>
                {
                    b.Navigation("CharacteristicVariants");

                    b.Navigation("Orders");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.ProductCategory", b =>
                {
                    b.Navigation("DeviceModels");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.ProductCharacteristic", b =>
                {
                    b.Navigation("CharacteristicVariants");
                });

            modelBuilder.Entity("istore_api.src.Domain.Models.ProductImage", b =>
                {
                    b.Navigation("OptionsCombiningCharacteristic");
                });
#pragma warning restore 612, 618
        }
    }
}
